AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infra domain stack for cumulus (network, compute)'

Parameters:
  Env:
    Type: String
    Description: Deployment environment (e.g., dev, staging, prod)

Resources:
  # VPC and networking (example - uses existing module)
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../modules/vpc.yaml
      Parameters:
        Env: !Ref Env

# Add other infra nested stacks here, e.g., ec2, security groups

Outputs:
  # Bubble up any infra outputs as needed
  VpcId:
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
