Parameters:
  Env:
    Type: String
  VpcCidr:
    Type: String
  PublicSubnetCidr:
    Type: String
  PrivateSubnetCidr:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/91a5b6fee00406f0b1fabd79e2c387ed.template
      Parameters:
        Env:
          Ref: Env
        VpcCidr:
          Ref: VpcCidr
        PublicSubnetCidr:
          Ref: PublicSubnetCidr
        PrivateSubnetCidr:
          Ref: PrivateSubnetCidr
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/88179c73ae1390d9644371df19405ee3.template
      Parameters:
        Env:
          Ref: Env
  SQS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/140ac18a6e014848e436325d686c6483.template
  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/73152214233209330db799e1410e51b8.template
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/ee4a281ba38b747191117e6be27a73e8.template
      Parameters:
        SubnetId:
          Fn::GetAtt:
          - VPC
          - Outputs.PublicSubnetId
        SecurityGroupId:
          Fn::GetAtt:
          - VPC
          - Outputs.SecurityGroupId
        KeyName:
          Ref: KeyName
