AWSTemplateFormatVersion: '2010-09-09'
Description: 'Common Layer - IAM Role, IAM Policy, and SSM Parameters'

Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
  
  ApplicationName:
    Type: String
    Description: Name of the application
  
  SSMParameterValue:
    Type: String
    Description: Value to store in SSM Parameter
    NoEcho: true

Conditions:
  # Condition to check if environment is dev
  IsDevEnvironment: !Equals [!Ref Environment, 'dev']

Resources:
  # IAM Role for Lambda
  LambdaRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/iam-role.yaml
      Parameters:
        RoleName: !Sub '${ApplicationName}-${Environment}-lambda-role'
        ServicePrincipal: lambda.amazonaws.com
        ManagedPolicyArns: 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  # IAM Policy 1 for Lambda (Base policy - always created)
  LambdaPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/iam-policy.yaml
      Parameters:
        PolicyName: !Sub '${ApplicationName}-${Environment}-lambda-policy'
        PolicyDocument: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "ssm:GetParameter",
                  "ssm:GetParameters"
                ],
                "Resource": "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ApplicationName}/${Environment}/*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:ListBucket",
                  "s3:GetObject",
                  "s3:PutObject"
                ],
                "Resource": [
                  "arn:aws:s3:::*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "kms:Decrypt",
                  "kms:GenerateDataKey"
                ],
                "Resource": "*"
              }
            ]
          }
        RoleName: !GetAtt LambdaRole.Outputs.RoleName

  # IAM Policy 2 for Lambda (Additional policy - only for dev)
  LambdaPolicy2:
    Type: AWS::CloudFormation::Stack
    Condition: IsDevEnvironment
    Properties:
      TemplateURL: ../modules/iam-policy.yaml
      Parameters:
        PolicyName: !Sub '${ApplicationName}-${Environment}-lambda-policy-2'
        PolicyDocument: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "dynamodb:GetItem",
                  "dynamodb:PutItem",
                  "dynamodb:UpdateItem",
                  "dynamodb:Query",
                  "dynamodb:Scan"
                ],
                "Resource": "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "sqs:SendMessage",
                  "sqs:ReceiveMessage",
                  "sqs:DeleteMessage"
                ],
                "Resource": "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "sns:Publish"
                ],
                "Resource": "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*"
              }
            ]
          }
        RoleName: !GetAtt LambdaRole.Outputs.RoleName

  # SSM Parameter
  SSMParameter:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/ssm-parameter.yaml
      Parameters:
        ParameterName: !Sub '/${ApplicationName}/${Environment}/config'
        ParameterValue: !Ref SSMParameterValue
        ParameterType: String
        Description: !Sub 'Configuration parameter for ${ApplicationName} ${Environment}'

Outputs:
  LambdaRoleArn:
    Description: Lambda IAM Role ARN
    Value: !GetAtt LambdaRole.Outputs.RoleArn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'
  
  LambdaRoleName:
    Description: Lambda IAM Role Name
    Value: !GetAtt LambdaRole.Outputs.RoleName
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleName'
  
  LambdaPolicyArn:
    Description: Lambda IAM Policy ARN
    Value: !GetAtt LambdaPolicy.Outputs.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaPolicyArn'
  
  LambdaPolicy2Arn:
    Description: Lambda IAM Policy 2 ARN (only in dev)
    Value: !If [IsDevEnvironment, !GetAtt LambdaPolicy2.Outputs.PolicyArn, 'N/A']
    Export:
      Name: !Sub '${AWS::StackName}-LambdaPolicy2Arn'
  
  SSMParameterName:
    Description: SSM Parameter Name
    Value: !GetAtt SSMParameter.Outputs.ParameterName
    Export:
      Name: !Sub '${AWS::StackName}-SSMParameterName'
  
  SSMParameterArn:
    Description: SSM Parameter ARN
    Value: !GetAtt SSMParameter.Outputs.ParameterArn
    Export:
      Name: !Sub '${AWS::StackName}-SSMParameterArn'
