AWSTemplateFormatVersion: '2010-09-09'
Description: Functional Group 2 - API Gateway, Lambda Function, S3 Bucket and KMS
  Key
Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
    - dev
    - staging
    - prod
  ApplicationName:
    Type: String
    Description: Name of the application
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda code
  LambdaCodeKey:
    Type: String
    Description: S3 key for Lambda code zip file
  LambdaRoleArn:
    Type: String
    Description: IAM Role ARN for Lambda from Common Layer
  SSMParameterName:
    Type: String
    Description: SSM Parameter Name from Common Layer
Resources:
  KMSKey:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/2c94ecd072abdd4af1018471a2eb267b.template
      Parameters:
        KeyAlias:
          Fn::Sub: ${ApplicationName}-${Environment}-s3-key-2
        Description:
          Fn::Sub: KMS key for ${ApplicationName} ${Environment} S3 bucket encryption
            (Group 2)
        EnableKeyRotation: 'true'
        PrincipalArns:
          Ref: LambdaRoleArn
  S3Bucket:
    Type: AWS::CloudFormation::Stack
    DependsOn: KMSKey
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/73b9b0d13cdf10015e8fc8293de1c91d.template
      Parameters:
        BucketName:
          Fn::Sub: ${ApplicationName}-${Environment}-data-bucket-2
        KmsKeyId:
          Fn::GetAtt:
          - KMSKey
          - Outputs.KeyId
        VersioningEnabled: Enabled
        PublicAccessBlock: 'true'
        LifecycleExpirationDays: 90
  LambdaFunction:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - S3Bucket
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/a1604b03fda9958d641ef718154f7a0d.template
      Parameters:
        FunctionName:
          Fn::Sub: ${ApplicationName}-${Environment}-function-2
        Runtime: python3.11
        Handler: index.handler
        CodeS3Bucket:
          Ref: LambdaCodeBucket
        CodeS3Key:
          Ref: LambdaCodeKey
        RoleArn:
          Ref: LambdaRoleArn
        MemorySize: 256
        Timeout: 60
        Environment:
          Ref: Environment
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    DependsOn: LambdaFunction
    Properties:
      TemplateURL: https://s3.us-west-1.amazonaws.com/cfn-artifacts-us-west-1/8de436a195b01cb7f0143efe03f590e0.template
      Parameters:
        ApiName:
          Fn::Sub: ${ApplicationName}-${Environment}-api-2
        StageName:
          Ref: Environment
        LambdaFunctionArn:
          Fn::GetAtt:
          - LambdaFunction
          - Outputs.FunctionArn
        ThrottlingBurstLimit: 5000
        ThrottlingRateLimit: 10000
Outputs:
  KMSKeyId:
    Description: KMS Key ID
    Value:
      Fn::GetAtt:
      - KMSKey
      - Outputs.KeyId
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-KMSKeyId
  KMSKeyArn:
    Description: KMS Key ARN
    Value:
      Fn::GetAtt:
      - KMSKey
      - Outputs.KeyArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-KMSKeyArn
  S3BucketName:
    Description: S3 Bucket Name
    Value:
      Fn::GetAtt:
      - S3Bucket
      - Outputs.BucketName
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-S3BucketName
  S3BucketArn:
    Description: S3 Bucket ARN
    Value:
      Fn::GetAtt:
      - S3Bucket
      - Outputs.BucketArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-S3BucketArn
  ApiUrl:
    Description: API Gateway URL
    Value:
      Fn::GetAtt:
      - ApiGateway
      - Outputs.ApiUrl
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ApiUrl
  ApiId:
    Description: API Gateway ID
    Value:
      Fn::GetAtt:
      - ApiGateway
      - Outputs.ApiId
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ApiId
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Outputs.FunctionArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LambdaFunctionArn
  LambdaFunctionName:
    Description: Lambda Function Name
    Value:
      Fn::GetAtt:
      - LambdaFunction
      - Outputs.FunctionName
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LambdaFunctionName
