AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Layer - S3 buckets using generic IAM modules'

Parameters:
  Env:
    Type: String
    Description: Deployment environment (e.g., dev, staging, prod)
  
  EnableVersioning:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable versioning for S3 buckets
  
  EnableEncryption:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable encryption for S3 buckets

Conditions:
  EnableVersioningCondition: !Equals [ !Ref EnableVersioning, "true" ]
  EnableEncryptionCondition: !Equals [ !Ref EnableEncryption, "true" ]

Resources:
  # ========================================
  # IAM POLICY (Generic Module)
  # ========================================
  IAMPolicy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/iam-policy.yaml
      Parameters:
        Environment: !Ref Env
        BaseName: !Ref AWS::StackName
        PolicyBaseName: s3

  # ========================================
  # IAM ROLE (Generic Module)
  # ========================================
  IAMRole:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMPolicy
    Properties:
      TemplateURL: ../modules/iam-role.yaml
      Parameters:
        RoleName: !Sub '${AWS::StackName}-s3-role-${Env}'
        AssumeRoleServicePrincipal: ec2.amazonaws.com,lambda.amazonaws.com
        ReadOnlyPolicyArn: !GetAtt IAMPolicy.Outputs.ReadOnlyPolicyArn
        GuardrailPolicyArn: !GetAtt IAMPolicy.Outputs.GuardrailPolicyArn
        MaxSessionDuration: 3600

  # ========================================
  # S3 BUCKET
  # ========================================
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-data-${Env}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: !If [ EnableVersioningCondition, "Enabled", "Suspended" ]
      BucketEncryption:
        !If
          - EnableEncryptionCondition
          - ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256
          - !Ref AWS::NoValue
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Layer
          Value: S3

  # Bucket Policy
  DataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${DataBucket.Arn}'
              - !Sub '${DataBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

Outputs:
  S3RoleArn:
    Description: ARN of S3 access role
    Value: !GetAtt IAMRole.Outputs.RoleArn
    Export:
      Name: !Sub '${AWS::StackName}-S3RoleArn'
  
  S3PolicyArn:
    Description: ARN of S3 access policy
    Value: !GetAtt IAMPolicy.Outputs.ReadOnlyPolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-S3PolicyArn'
  
  S3InstanceProfileArn:
    Description: ARN of S3 access instance profile
    Value: !GetAtt IAMRole.Outputs.InstanceProfileArn
    Export:
      Name: !Sub '${AWS::StackName}-S3InstanceProfileArn'
  
  DataBucketName:
    Description: Name of the data bucket
    Value: !Ref DataBucket
    Export:
      Name: !Sub '${AWS::StackName}-DataBucketName'
  
  DataBucketArn:
    Description: ARN of the data bucket
    Value: !GetAtt DataBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DataBucketArn'
