AWSTemplateFormatVersion: '2010-09-09'
Description: 'Root stack for cumulus - orchestrates common layer and functional group layers'

Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
  
  ApplicationName:
    Type: String
    Description: Name of the application
    Default: cumulus
  
  # Common Layer Parameters (IAM + SSM)
  SSMParameterValue:
    Type: String
    Description: Value to store in SSM Parameter
    NoEcho: true
    Default: 'default-config-value'
  
  # Functional Group Parameters (Lambda)
  LambdaCodeBucket:
    Type: String
    Description: S3 bucket containing Lambda code
  
  LambdaCodeKey:
    Type: String
    Description: S3 key for Lambda code zip file
    Default: 'lambda-code.zip'

Resources:
  # ========================================
  # COMMON LAYER (Deploy First - IAM + SSM)
  # ========================================
  CommonLayer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../layers/common-layer.yaml
      Parameters:
        Environment: !Ref Environment
        ApplicationName: !Ref ApplicationName
        SSMParameterValue: !Ref SSMParameterValue
      Tags:
        - Key: Layer
          Value: Common
        - Key: Environment
          Value: !Ref Environment

  # ========================================
  # FUNCTIONAL GROUP 1 (Deploy Second - API Gateway + Lambda + S3 + KMS)
  # ========================================
  FunctionalGroup1:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonLayer
    Properties:
      TemplateURL: ../../layers/functional-group1.yaml
      Parameters:
        Environment: !Ref Environment
        ApplicationName: !Ref ApplicationName
        LambdaCodeBucket: !Ref LambdaCodeBucket
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaRoleArn: !GetAtt CommonLayer.Outputs.LambdaRoleArn
        SSMParameterName: !GetAtt CommonLayer.Outputs.SSMParameterName
      Tags:
        - Key: Layer
          Value: FunctionalGroup1
        - Key: Environment
          Value: !Ref Environment

  # ========================================
  # FUNCTIONAL GROUP 2 (Deploy Third - API Gateway + Lambda + S3 + KMS)
  # ========================================
  FunctionalGroup2:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonLayer
    Properties:
      TemplateURL: ../../layers/functional-group2.yaml
      Parameters:
        Environment: !Ref Environment
        ApplicationName: !Ref ApplicationName
        LambdaCodeBucket: !Ref LambdaCodeBucket
        LambdaCodeKey: !Ref LambdaCodeKey
        LambdaRoleArn: !GetAtt CommonLayer.Outputs.LambdaRoleArn
        SSMParameterName: !GetAtt CommonLayer.Outputs.SSMParameterName
      Tags:
        - Key: Layer
          Value: FunctionalGroup2
        - Key: Environment
          Value: !Ref Environment

Outputs:
  # Common Layer Outputs (IAM + SSM)
  LambdaRoleArn:
    Description: Lambda IAM Role ARN
    Value: !GetAtt CommonLayer.Outputs.LambdaRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'
  
  LambdaRoleName:
    Description: Lambda IAM Role Name
    Value: !GetAtt CommonLayer.Outputs.LambdaRoleName
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleName'
  
  SSMParameterName:
    Description: SSM Parameter Name
    Value: !GetAtt CommonLayer.Outputs.SSMParameterName
    Export:
      Name: !Sub '${AWS::StackName}-SSMParameterName'
  
  # Functional Group 1 Outputs
  FunctionalGroup1ApiUrl:
    Description: Functional Group 1 API Gateway URL
    Value: !GetAtt FunctionalGroup1.Outputs.ApiUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-ApiUrl'
  
  FunctionalGroup1ApiId:
    Description: Functional Group 1 API Gateway ID
    Value: !GetAtt FunctionalGroup1.Outputs.ApiId
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-ApiId'
  
  FunctionalGroup1LambdaFunctionArn:
    Description: Functional Group 1 Lambda Function ARN
    Value: !GetAtt FunctionalGroup1.Outputs.LambdaFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-LambdaFunctionArn'
  
  FunctionalGroup1LambdaFunctionName:
    Description: Functional Group 1 Lambda Function Name
    Value: !GetAtt FunctionalGroup1.Outputs.LambdaFunctionName
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-LambdaFunctionName'
  
  FunctionalGroup1S3BucketName:
    Description: Functional Group 1 S3 Bucket Name
    Value: !GetAtt FunctionalGroup1.Outputs.S3BucketName
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-S3BucketName'
  
  FunctionalGroup1S3BucketArn:
    Description: Functional Group 1 S3 Bucket ARN
    Value: !GetAtt FunctionalGroup1.Outputs.S3BucketArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-S3BucketArn'
  
  FunctionalGroup1KMSKeyId:
    Description: Functional Group 1 KMS Key ID
    Value: !GetAtt FunctionalGroup1.Outputs.KMSKeyId
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-KMSKeyId'
  
  FunctionalGroup1KMSKeyArn:
    Description: Functional Group 1 KMS Key ARN
    Value: !GetAtt FunctionalGroup1.Outputs.KMSKeyArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup1-KMSKeyArn'
  
  # Functional Group 2 Outputs
  FunctionalGroup2ApiUrl:
    Description: Functional Group 2 API Gateway URL
    Value: !GetAtt FunctionalGroup2.Outputs.ApiUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-ApiUrl'
  
  FunctionalGroup2ApiId:
    Description: Functional Group 2 API Gateway ID
    Value: !GetAtt FunctionalGroup2.Outputs.ApiId
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-ApiId'
  
  FunctionalGroup2LambdaFunctionArn:
    Description: Functional Group 2 Lambda Function ARN
    Value: !GetAtt FunctionalGroup2.Outputs.LambdaFunctionArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-LambdaFunctionArn'
  
  FunctionalGroup2LambdaFunctionName:
    Description: Functional Group 2 Lambda Function Name
    Value: !GetAtt FunctionalGroup2.Outputs.LambdaFunctionName
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-LambdaFunctionName'
  
  FunctionalGroup2S3BucketName:
    Description: Functional Group 2 S3 Bucket Name
    Value: !GetAtt FunctionalGroup2.Outputs.S3BucketName
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-S3BucketName'
  
  FunctionalGroup2S3BucketArn:
    Description: Functional Group 2 S3 Bucket ARN
    Value: !GetAtt FunctionalGroup2.Outputs.S3BucketArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-S3BucketArn'
  
  FunctionalGroup2KMSKeyId:
    Description: Functional Group 2 KMS Key ID
    Value: !GetAtt FunctionalGroup2.Outputs.KMSKeyId
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-KMSKeyId'
  
  FunctionalGroup2KMSKeyArn:
    Description: Functional Group 2 KMS Key ARN
    Value: !GetAtt FunctionalGroup2.Outputs.KMSKeyArn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionalGroup2-KMSKeyArn'
