AWSTemplateFormatVersion: '2010-09-09'
Description: 'Reusable API Gateway REST API module'

Parameters:
  ApiName:
    Type: String
    Description: Name of the API Gateway
  
  StageName:
    Type: String
    Default: prod
    Description: API deployment stage name
  
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Lambda function to integrate
  
  ThrottlingBurstLimit:
    Type: Number
    Default: 5000
    Description: API throttling burst limit
  
  ThrottlingRateLimit:
    Type: Number
    Default: 10000
    Description: API throttling rate limit

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiName
      Description: !Sub 'API Gateway for ${ApiName}'
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: '{proxy+}'

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ApiResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations'

  RootApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !GetAtt RestApi.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionArn}/invocations'

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiMethod
      - RootApiMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref StageName
      StageDescription:
        ThrottlingBurstLimit: !Ref ThrottlingBurstLimit
        ThrottlingRateLimit: !Ref ThrottlingRateLimit

  LambdaApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*'

Outputs:
  ApiId:
    Description: API Gateway ID
    Value: !Ref RestApi
    Export:
      Name: !Sub '${AWS::StackName}-ApiId'
  
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'
  
  ApiArn:
    Description: API Gateway ARN
    Value: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiArn'
