Parameters:
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
