AWSTemplateFormatVersion: '2010-09-09'
Description: 'Reusable IAM Role module'

Parameters:
  RoleName:
    Type: String
    Description: Name of the IAM role
  
  ServicePrincipal:
    Type: String
    Description: Service principal that can assume this role
    Default: lambda.amazonaws.com
  
  ManagedPolicyArns:
    Type: CommaDelimitedList
    Description: Comma-separated list of managed policy ARNs to attach
    Default: ''
  
  MaxSessionDuration:
    Type: Number
    Default: 3600
    MinValue: 3600
    MaxValue: 43200
    Description: Max session duration in seconds

Conditions:
  HasManagedPolicies: !Not [!Equals [!Join ['', !Ref ManagedPolicyArns], '']]

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: !Ref ServicePrincipal
            Action: 'sts:AssumeRole'
      ManagedPolicyArns: !If [HasManagedPolicies, !Ref ManagedPolicyArns, !Ref AWS::NoValue]
      Tags:
        - Key: Name
          Value: !Ref RoleName

Outputs:
  RoleArn:
    Description: IAM Role ARN
    Value: !GetAtt IAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: IAM Role Name
    Value: !Ref IAMRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
