AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policies Module - Generic policies for multiple applications'

Resources:
  # ========================================
  # APPLICATION 1 POLICY
  # ========================================
  
  Application1ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'App1-ReadOnly'
      Description: Read-only policy for Application1 resources
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: App1S3ReadOnly
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketLocation'
            Resource:
              - 'arn:aws:s3:::app1-*'
              - 'arn:aws:s3:::app1-*/*'
          
          - Sid: App1LambdaReadOnly
            Effect: Allow
            Action:
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:ListFunctions'
              - 'lambda:ListAliases'
            Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:app1-*'
          
          - Sid: App1SQSReadOnly
            Effect: Allow
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:ListQueues'
              - 'sqs:ReceiveMessage'
            Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:app1-*'
          
          - Sid: App1CloudFormationReadOnly
            Effect: Allow
            Action:
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:DescribeStackEvents'
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:ListStacks'
            Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/app1-*'
          
          - Sid: App1CloudWatchReadOnly
            Effect: Allow
            Action:
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:GetMetricStatistics'
            Resource: '*'
          
          - Sid: App1EC2ReadOnly
            Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeVpcs'
            Resource: '*'

  # ========================================
  # APPLICATION 2 POLICY
  # ========================================
  
  Application2ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'App2-ReadOnly'
      Description: Read-only policy for Application2 resources
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: App2S3ReadOnly
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketLocation'
            Resource:
              - 'arn:aws:s3:::app2-*'
              - 'arn:aws:s3:::app2-*/*'
          
          - Sid: App2LambdaReadOnly
            Effect: Allow
            Action:
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:ListFunctions'
              - 'lambda:ListAliases'
            Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:app2-*'
          
          - Sid: App2SQSReadOnly
            Effect: Allow
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:ListQueues'
              - 'sqs:ReceiveMessage'
            Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:app2-*'
          
          - Sid: App2CloudFormationReadOnly
            Effect: Allow
            Action:
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:DescribeStackEvents'
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:ListStacks'
            Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/app2-*'
          
          - Sid: App2CloudWatchReadOnly
            Effect: Allow
            Action:
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:GetMetricStatistics'
            Resource: '*'
          
          - Sid: App2EC2ReadOnly
            Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeVpcs'
            Resource: '*'

  # ========================================
  # GUARDRAIL POLICY (Deny - for all applications)
  # ========================================
  
  ReadOnlyGuardrailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: 'ReadOnly-Guardrail'
      Description: Deny policy to restrict dangerous actions - enforces read-only access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyDangerousEC2Actions
            Effect: Deny
            Action:
              - 'ec2:TerminateInstances'
              - 'ec2:DeleteVolume'
              - 'ec2:StopInstances'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'
              - 'ec2:AuthorizeSecurityGroupIngress'
            Resource: '*'
          
          - Sid: DenyDangerousS3Actions
            Effect: Deny
            Action:
              - 's3:DeleteBucket'
              - 's3:DeleteObject'
              - 's3:PutBucketPolicy'
              - 's3:PutObject'
            Resource: '*'
          
          - Sid: DenyDangerousLambdaActions
            Effect: Deny
            Action:
              - 'lambda:DeleteFunction'
              - 'lambda:UpdateFunctionCode'
              - 'lambda:PublishVersion'
            Resource: '*'
          
          - Sid: DenyDangerousSQSActions
            Effect: Deny
            Action:
              - 'sqs:DeleteQueue'
              - 'sqs:PurgeQueue'
              - 'sqs:SendMessage'
            Resource: '*'
          
          - Sid: DenyCloudFormationModification
            Effect: Deny
            Action:
              - 'cloudformation:CreateStack'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:DeleteStack'
            Resource: '*'
          
          - Sid: DenyIAMModification
            Effect: Deny
            Action:
              - 'iam:*'
            Resource: '*'

Outputs:
  # Export all policies - app.yaml will choose which to use
  Application1PolicyArn:
    Description: ARN of Application1 read-only policy
    Value: !GetAtt Application1ReadOnlyPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-App1PolicyArn'

  Application2PolicyArn:
    Description: ARN of Application2 read-only policy
    Value: !GetAtt Application2ReadOnlyPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-App2PolicyArn'

  GuardrailPolicyArn:
    Description: ARN of guardrail deny policy (applied to all roles)
    Value: !GetAtt ReadOnlyGuardrailPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-GuardrailPolicyArn'
