AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policies Module - Generic policies for multiple applications'

Parameters:
  Environment:
    Type: String
    Default: ""
    Description: Optional environment suffix to ensure unique ManagedPolicy names (e.g., dev, staging)
  BaseName:
    Type: String
    Default: ""
    Description: Base name to scope resources and build names (pass parent stack name)
  PolicyBaseName:
    Type: String
    Default: "readonly"
    Description: Logical policy name segment to include in ManagedPolicy name (e.g., readonly)

Conditions:
  HasEnvironment: !Not [ !Equals [ !Ref Environment, "" ] ]

Resources:
  # ========================================
  # GENERIC READ-ONLY POLICY
  # ========================================
  GenericReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !If 
        - HasEnvironment
        - !Sub 
          - '${Base}-${Env}-${PolicyBase}-${Unique}'
          - {
              Base: !Ref BaseName,
              Env: !Ref Environment,
              PolicyBase: !Ref PolicyBaseName,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
        - !Sub 
          - '${Base}-${PolicyBase}-${Unique}'
          - {
              Base: !Ref BaseName,
              PolicyBase: !Ref PolicyBaseName,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
      Description: Generic read-only policy scoped to resources by BaseName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ReadOnly
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketLocation'
            Resource:
              - !Sub 'arn:aws:s3:::${BaseName}-*'
              - !Sub 'arn:aws:s3:::${BaseName}-*/*'
          - Sid: LambdaReadOnly
            Effect: Allow
            Action:
              - 'lambda:GetFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'lambda:ListFunctions'
              - 'lambda:ListAliases'
            Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:${BaseName}-*'
          - Sid: SQSReadOnly
            Effect: Allow
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:ListQueues'
              - 'sqs:ReceiveMessage'
            Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:${BaseName}-*'
          - Sid: CloudFormationReadOnly
            Effect: Allow
            Action:
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:DescribeStackEvents'
              - 'cloudformation:DescribeStackResource'
              - 'cloudformation:ListStacks'
            Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/${BaseName}-*'
          - Sid: CloudWatchReadOnly
            Effect: Allow
            Action:
              - 'logs:Describe*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:GetMetricStatistics'
            Resource: '*'
          - Sid: EC2ReadOnly
            Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeVpcs'
            Resource: '*'

  # ========================================
  # GUARDRAIL POLICY (Deny - for all applications)
  # ========================================
  
  ReadOnlyGuardrailPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !If 
        - HasEnvironment
        - !Sub 
          - '${Base}-${Env}-guardrail-${Unique}'
          - {
              Base: !Ref BaseName,
              Env: !Ref Environment,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
        - !Sub 
          - '${Base}-guardrail-${Unique}'
          - {
              Base: !Ref BaseName,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
      Description: Deny policy to restrict dangerous actions - enforces read-only access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyDangerousEC2Actions
            Effect: Deny
            Action:
              - 'ec2:TerminateInstances'
              - 'ec2:DeleteVolume'
              - 'ec2:StopInstances'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DeleteSecurityGroup'
              - 'ec2:AuthorizeSecurityGroupIngress'
            Resource: '*'
          
          - Sid: DenyDangerousS3Actions
            Effect: Deny
            Action:
              - 's3:DeleteBucket'
              - 's3:DeleteObject'
              - 's3:PutBucketPolicy'
              - 's3:PutObject'
            Resource: '*'
          
          - Sid: DenyDangerousLambdaActions
            Effect: Deny
            Action:
              - 'lambda:DeleteFunction'
              - 'lambda:UpdateFunctionCode'
              - 'lambda:PublishVersion'
            Resource: '*'
          
          - Sid: DenyDangerousSQSActions
            Effect: Deny
            Action:
              - 'sqs:DeleteQueue'
              - 'sqs:PurgeQueue'
              - 'sqs:SendMessage'
            Resource: '*'
          
          - Sid: DenyCloudFormationModification
            Effect: Deny
            Action:
              - 'cloudformation:CreateStack'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:DeleteStack'
            Resource: '*'
          
          - Sid: DenyIAMModification
            Effect: Deny
            Action:
              - 'iam:*'
            Resource: '*'

  # ========================================
  # S3 LIST POLICY (Optional - for specific environments)
  # ========================================
  S3ListPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !If 
        - HasEnvironment
        - !Sub 
          - '${Base}-${Env}-s3-list-${Unique}'
          - {
              Base: !Ref BaseName,
              Env: !Ref Environment,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
        - !Sub 
          - '${Base}-s3-list-${Unique}'
          - {
              Base: !Ref BaseName,
              Unique: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref 'AWS::StackId' ] ] ] ]
            }
      Description: S3 list all buckets policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 's3:ListAllMyBuckets'
            Resource: '*'

Outputs:
  # Export policy ARNs - parent template will choose which to use
  ReadOnlyPolicyArn:
    Description: ARN of generic read-only policy
    Value: !GetAtt GenericReadOnlyPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-ReadOnlyPolicyArn'

  GuardrailPolicyArn:
    Description: ARN of guardrail deny policy (applied to all roles)
    Value: !GetAtt ReadOnlyGuardrailPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-GuardrailPolicyArn'

  S3ListPolicyArn:
    Description: ARN of S3 list all buckets policy
    Value: !GetAtt S3ListPolicy.PolicyArn
    Export:
      Name: !Sub '${AWS::StackName}-S3ListPolicyArn'
