AWSTemplateFormatVersion: '2010-09-09'
Description: 'Reusable IAM Policy module'

Parameters:
  PolicyName:
    Type: String
    Description: Name of the IAM policy
  
  PolicyDocument:
    Type: String
    Description: IAM policy document in JSON format
  
  RoleName:
    Type: String
    Description: Name of the IAM role to attach this policy to

Resources:
  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref PolicyName
      PolicyDocument: !Ref PolicyDocument
      Roles:
        - !Ref RoleName

Outputs:
  PolicyName:
    Description: IAM Policy Name
    Value: !Ref IAMPolicy
    Export:
      Name: !Sub '${AWS::StackName}-PolicyName'
  
  PolicyArn:
    Description: IAM Policy ARN
    Value: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${PolicyName}'
    Export:
      Name: !Sub '${AWS::StackName}-PolicyArn'
