AWSTemplateFormatVersion: '2010-09-09'
Description: 'Retina application - function-based layers (VPC, Lambda, S3)'

Parameters:
  Env:
    Type: String
    Description: Deployment environment (e.g., dev, staging, prod)
  
  VpcCidr:
    Type: String
    Default: 10.1.0.0/16
    Description: CIDR block for VPC
  
  PublicSubnetCidr:
    Type: String
    Default: 10.1.1.0/24
    Description: CIDR block for public subnet
  
  PrivateSubnetCidr:
    Type: String
    Default: 10.1.2.0/24
    Description: CIDR block for private subnet
  
  DeployVpcLayer:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Deploy VPC layer
  
  DeployS3Layer:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Deploy S3 layer
  
  DeployLambdaLayer:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Deploy Lambda layer

Conditions:
  ShouldDeployVpc: !Equals [ !Ref DeployVpcLayer, "true" ]
  ShouldDeployS3: !Equals [ !Ref DeployS3Layer, "true" ]
  ShouldDeployLambda: !Equals [ !Ref DeployLambdaLayer, "true" ]

Resources:
  # ========================================
  # VPC LAYER (Foundation)
  # ========================================
  VpcLayer:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployVpc
    Properties:
      TemplateURL: ../../layers/vpc-layer.yaml
      Parameters:
        Env: !Ref Env
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
        EnableNatGateway: "true"

  # ========================================
  # S3 LAYER
  # ========================================
  S3Layer:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployS3
    Properties:
      TemplateURL: ../../layers/s3-layer.yaml
      Parameters:
        Env: !Ref Env
        EnableVersioning: "true"
        EnableEncryption: "true"

  # ========================================
  # LAMBDA LAYER
  # ========================================
  LambdaLayer:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldDeployLambda
    Properties:
      TemplateURL: ../../layers/lambda-layer.yaml
      Parameters:
        Env: !Ref Env
        LambdaCodeBucket: ""
        LambdaCodeKey: "retina-lambda.zip"

Outputs:
  # VPC Outputs
  VpcId:
    Condition: ShouldDeployVpc
    Description: VPC ID
    Value: !GetAtt VpcLayer.Outputs.VpcId
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
  
  # S3 Outputs
  DataBucketName:
    Condition: ShouldDeployS3
    Description: S3 data bucket name
    Value: !GetAtt S3Layer.Outputs.DataBucketName
    Export:
      Name: !Sub '${AWS::StackName}-DataBucketName'
  
  S3RoleArn:
    Condition: ShouldDeployS3
    Description: S3 access role ARN
    Value: !GetAtt S3Layer.Outputs.S3RoleArn
    Export:
      Name: !Sub '${AWS::StackName}-S3RoleArn'
  
  # Lambda Outputs
  LambdaRoleArn:
    Condition: ShouldDeployLambda
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaLayer.Outputs.LambdaRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'
